### ISSUE TITLE
quizz end whitout working ( solved )

### ISSUE THREAD

**Issue by goldenpeps** [GamrayW/7sleeping#5]
I had an old version which no longer works, I wanted to update it with the latest update and since then, I have had an error saying that the quiz is finished. The button remains red/pink in color. 

Here are all the steps I took to find a solution:
- uninstall tapermonkey and reinstall.
- clear caches 
- empty cookies 
- try the answers directly in the console 

I don't, it's not what it's due to, if it's on my side or if it's the extension 

![image](https://github.com/user-attachments/assets/4939bbd5-45ad-4414-8a9b-8665dc8e2a07)
![image](https://github.com/user-attachments/assets/946cad3c-6203-4c7e-a8f0-7cbcd1bc34c0)

https://github.com/user-attachments/assets/6ba16d5e-deee-480b-9f78-52738a34230d

thank you for paying attention to this problem

**Comment by goldenpeps** [comment]
thank you for responding, I just tried with the new version and the problem persists, whether on Firefox or on Chrome 
looking at tampermonkey the only time is this 
![image](https://github.com/user-attachments/assets/6f31d1d1-79b1-48b1-8d87-27738fd1d7a2)
I don't think it comes here at the moment I use this code in cosole  
for the first question

```
let answer = (curr_kc => { while (!curr_kc.memoizedProps?.answerOptions) curr_kc = curr_kc.return; return curr_kc.memoizedProps.answerOptions.answer[0].value })(document.querySelector(".question")[Object.keys(document.querySelector(".question"))[0]]);
```
and if that's not enough 

```
  var  rslt = false 

if (rslt== false){
let question_div = document.querySelector(".question")
rslt= true
        let reactKey = Object.keys(question_div)[0]

        let curr_kc = question_div[reactKey]
        while (curr_kc.memoizedProps.answerOptions == undefined) {
            curr_kc = curr_kc.return
        }

        curr_kc.memoizedProps.answerOptions.answer[0].value
}
else{
  while (curr_kc.memoizedProps.answerOptions == undefined) {
            curr_kc = curr_kc.return
        }

        curr_kc.memoizedProps.answerOptions.answer[0].value

}

```

**Comment by GamrayW** [comment]
I managed to re-create your bug, I fixed some logic errors and it now works good on my end with the latest update (0.9.2).

**Comment by goldenpeps** [comment]
the bug has been fixed, I will look at the code and try to understand, thank you for taking the time to correct my problem
